[package]
name = "pledge_nif"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "pledge_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.26.0"
openbsd = "0.1.2"
